---
name: CI
on: [push, pull_request, workflow_dispatch]
env:
  FORCE_COLOR: "1"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10"]
        include:
          - { os: ubuntu-latest, python-version: "3.7" }
          - { os: ubuntu-latest, python-version: "3.8" }
          - { os: ubuntu-latest, python-version: "3.9" }
          - os: ubuntu-latest
            python-version: "3.11"
            python-install-version: 3.11-dev
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Prepare environment
        uses: ./.github/actions/prepare_ci
      - name: Run tests (latest)
        run: >-
          nox
          --error-on-missing-interpreters
          --force-python ${{ matrix.python-version }}
          -s 'test-${{ matrix.python-version }}(latest)'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
      - name: Run tests (minimum versions)
        run: >-
          nox
          --error-on-missing-interpreters
          --force-python ${{ matrix.python-version }}
          -s 'test-${{ matrix.python-version }}(minimum-versions)'
  type-check:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10"]
        include:
          - { os: ubuntu-latest, python-version: "3.7" }
          - { os: ubuntu-latest, python-version: "3.8" }
          - { os: ubuntu-latest, python-version: "3.9" }
          - os: ubuntu-latest
            python-version: "3.11"
            python-install-version: 3.11-dev
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Prepare environment
        uses: ./.github/actions/prepare_ci
      - name: Install Node 16 for Pyright
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Type check
        run: >-
          nox
          --error-on-missing-interpreters
          --force-python ${{ matrix.python-version }}
          -s type_check
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Install nox
        run: pipx install nox
      - name: Install Node 16 for Prettier
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Check code formatting
        run: nox -s format -- --check
